version: '3.1'

services:
app:
  build: .
  entrypoint: .docker/entrypoint.sh
  container_name: courses-app
  ports:
    - "3000:3000"
  volumes:
    - .:/home/node/app
  depends_on:
    - db

  db:
    build: .docker/postgres
    container_name: courses-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=courses

  dbtest:
    build: .docker/postgres
    container_name: courses-test-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=courses
